# Generated by Django 4.2.4 on 2025-04-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='english',
            options={'verbose_name': 'english'},
        ),
    ]
