# Generated by Django 4.2.4 on 2025-04-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_english_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English',
            new_name='englishWords',
        ),
        migrations.AlterModelOptions(
            name='englishwords',
            options={'verbose_name': 'english_words'},
        ),
    ]
