# Generated by Django 4.2.4 on 2025-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_english_englishwords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='lang_code',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
