# Generated by Django 4.2.4 on 2025-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_englishwords_lang_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='hindiWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='hi', max_length=10)),
                ('words', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'hindi_words',
            },
        ),
        migrations.CreateModel(
            name='japaneseWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='ja', max_length=10)),
                ('words', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'japanese_words',
            },
        ),
        migrations.CreateModel(
            name='russianWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(default='ru', max_length=10)),
                ('words', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'russian_words',
            },
        ),
    ]
